export const DASHBOARD = "DASHBOARD";
export const SIGNUP = "SIGNUP";
export const LOGIN = "LOGIN"
export const TASKS_LIST_OLD_UI = "TASKS LIST - OLD UI";
export const MY_TASKS = "MY TASKS";
export const NOTIFICATIONS = "NOTIFICATIONS";
export const ABOUT = "ABOUT";
export const ERROR_PAGE = "ERROR PAGE";
export const PROFILE = "PROFILE";
export const SETTINGS = "SETTINGS";
